apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
    name: es-operator-catalog
    namespace: openshift-marketplace
spec:
    displayName: IBM ES Catalog
    image: icr.io/cpopen/ibm-eventstreams-catalog:v3.4.0
    publisher: IBM
    sourceType: grpc
    updateStrategy:
        registryPoll:
            interval: 45m
