apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-orders
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '524288000'
  partitions: 3
  replicas: 3
  topicName: ORDERS.NEW

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-cancellations
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '524288000'
  partitions: 3
  replicas: 3
  topicName: CANCELLATIONS

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-badgeevents
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '524288000'
  partitions: 3
  replicas: 1
  topicName: DOOR.BADGEIN

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-stockmovement
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '524288000'
  partitions: 3
  replicas: 1
  topicName: STOCK.MOVEMENT

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-customers
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '524288000'
  partitions: 3
  replicas: 3
  topicName: CUSTOMERS.NEW

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-sensorreadings
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '524288000'
  partitions: 3
  replicas: 1
  topicName: SENSOR.READINGS

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-onlineorders
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '524288000'
  partitions: 3
  replicas: 3
  topicName: ONLINE.ORDERS.NEW

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-outofstocks
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '524288000'
  partitions: 3
  replicas: 3
  topicName: OUT.OF.STOCK

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-orders-avro
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '50000000'
  partitions: 3
  replicas: 1
  topicName: ORDERS.NEW.AVRO

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-cancellations-avro
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '50000000'
  partitions: 3
  replicas: 1
  topicName: CANCELLATIONS.AVRO

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-badgeevents-avro
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '50000000'
  partitions: 3
  replicas: 1
  topicName: DOOR.BADGEIN.AVRO

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-stockmovement-avro
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '50000000'
  partitions: 3
  replicas: 1
  topicName: STOCK.MOVEMENT.AVRO

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-customers-avro
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '50000000'
  partitions: 3
  replicas: 1
  topicName: CUSTOMERS.NEW.AVRO

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-sensorreadings-avro
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '50000000'
  partitions: 3
  replicas: 1
  topicName: SENSOR.READINGS.AVRO

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-onlineorders-avro
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '50000000'
  partitions: 3
  replicas: 1
  topicName: ONLINE.ORDERS.NEW.AVRO

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-outofstocks-avro
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '50000000'
  partitions: 3
  replicas: 1
  topicName: OUT.OF.STOCK.AVRO
