apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnect
metadata:
  annotations:
    eventstreams.ibm.com/use-connector-resources: 'true'
  name: kafka-connect-cluster
spec:
  config:
    group.id: kafka-connect
    client.id: kafka-connect-client
    config.storage.topic: connect-configs
    offset.storage.topic: connect-offsets
    status.storage.topic: connect-status
  bootstrapServers: 'my-kafka-cluster-kafka-bootstrap.{{ eventautomation_namespace }}.svc:9095'
  resources:
    limits:
      cpu: 2048m
      memory: 2Gi
    requests:
      cpu: 2048m
      memory: 2Gi
  authentication:
    passwordSecret:
      password: password
      secretName: kafka-connect-credentials
    type: scram-sha-512
    username: kafka-connect-credentials
  template:
    buildConfig:
      pullSecret: ibm-entitlement-key
    connectContainer:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
    pod:
      imagePullSecrets: []
      metadata:
        annotations:
          cloudpakId: c8b82d189e7545f0892db9ef2731b90d
          productVersion: 11.2.4
          productID: 2a79e49111f44ec3acd89608e56138f5
          cloudpakName: IBM Cloud Pak for Integration
          productChargedContainers: kafka-connect-cluster-connect
          productCloudpakRatio: '2:1'
          productName: IBM Event Streams for Non Production
          eventstreams.production.type: CloudPakForIntegrationNonProduction
          productMetric: VIRTUAL_PROCESSOR_CORE
  tls:
    trustedCertificates:
      - certificate: ca.crt
        secretName: my-kafka-cluster-cluster-ca-cert
  replicas: 1
  build:
    output:
      type: docker
      image: image-registry.openshift-image-registry.svc:5000/{{ eventautomation_namespace }}/event-automation-demo:0.0.1
    plugins:
      - name: datagen
        artifacts:
          - type: jar
            url: https://github.com/IBM/kafka-connect-loosehangerjeans-source/releases/download/0.0.1/kafka-connect-loosehangerjeans-source-0.0.1-jar-with-dependencies.jar
      - name: mq-source
        artifacts:
          - type: jar
            url: https://github.com/ibm-messaging/kafka-connect-mq-source/releases/download/v1.3.3/kafka-connect-mq-source-1.3.3-jar-with-dependencies.jar
