apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-credentials
data:
  consumer.properties: |-
    bootstrap.servers=my-kafka-cluster-kafka-bootstrap.{{ eventautomation_namespace }}.svc:9095
    group.id=kafka-performance-test
    security.protocol=SASL_SSL
    sasl.mechanism=SCRAM-SHA-512
    sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="workload-apps" password="{{ kafka_password }}";
    ssl.protocol=TLSv1.3
    ssl.truststore.location=/certs/cluster/ca.p12
    ssl.truststore.password={{ truststore_password }}
    ssl.truststore.type=PKCS12
  producer.properties: |-
    bootstrap.servers=my-kafka-cluster-kafka-bootstrap.{{ eventautomation_namespace }}.svc:9095
    compression.type=gzip
    linger.ms=500
    acks=0
    security.protocol=SASL_SSL
    sasl.mechanism=SCRAM-SHA-512
    sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="workload-apps" password="{{ kafka_password }}";
    ssl.protocol=TLSv1.3
    ssl.truststore.location=/certs/cluster/ca.p12
    ssl.truststore.password={{ truststore_password }}
    ssl.truststore.type=PKCS12
