kind: Grafana
apiVersion: grafana.integreatly.org/v1beta1
metadata:
  name: event-automation
  labels:
    dashboards: event-automation
    folders: event-automation
spec:
  route:
    spec: {}
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: admin
      admin_password: Th1$ISTh3Adm1nPa$SW0Rd
