---
- name: Prepare the Event Automation welcome page
  hosts: localhost
  connection: local
  vars:
    eventautomation_namespace: "event-automation"
    welcome_url_eventstreams: "placeholder"
    welcome_url_eventendpointmanagement: "placeholder"
    welcome_url_eventprocessing: "placeholder"
    api_url_eventendpointmanagement: "placeholder"
    certificate_eventendpointmanagement: "placeholder"

  tasks:
    - name: Install local pre-requisites
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/prerequisites.yaml"

    - name: Create namespace for Event Automation
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/setup-namespace.yaml"
      vars:
        namespace: "{{ eventautomation_namespace }}"

    - name: Setup welcome page
      kubernetes.core.k8s:
        validate_certs: false
        state: present
        namespace: "{{ eventautomation_namespace }}"
        template: "{{ playbook_dir }}/templates/01-configmap.yaml"
