{
 "title": "Event Endpoint Management (Health)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Uptime",
   "type": "table",
   "description": "Start time for each of the Event Endpoint Management pods",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "kube_pod_container_state_started{namespace=\"event-automation\", pod=~\"my-eem-manager-ibm-eem-manager-0|my-eem-gateway-ibm-egw-gateway-.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Manager services health",
   "type": "piechart",
   "description": "The number of internal services (e.g. storage provider, key management, etc.) in the Event Endpoint Management Manager that are currently ready. \n\nOnce startup is complete, all services should be ready. ",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eemmanager_services_ready{namespace=\"event-automation\"}",
     "legendFormat": "ready"
    },
    {
     "expr": "eemmanager_services_not_ready{namespace=\"event-automation\"}",
     "legendFormat": "not ready"
    }
   ]
  },
  {
   "title": "Event Manager API calls / second",
   "type": "timeseries",
   "description": "The number of HTTP API calls per second that the Event Manager is currently handling. \n\nThese are grouped by the response status code, to show whether there is a particular increase in specific types of API calls. ",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum by(statusCode) (rate(eemmanager_api_responses_total{namespace=\"event-automation\"}[$__rate_interval]))",
     "legendFormat": "HTTP {{statusCode}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "gauge",
   "description": "Number of restarts for each of the Event Endpoint Management pods. \n\nIf they are healthy, this should be zero.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container) (kube_pod_container_status_restarts_total{namespace=\"event-automation\", pod=~\"my-eem-manager-ibm-eem-manager-0|my-eem-gateway-ibm-egw-gateway-.*\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Event Manager",
   "type": "timeseries",
   "description": "Resource (CPU and memory) usage by the Event Manager pod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_user_seconds_total{namespace=\"event-automation\", pod=\"my-eem-manager-ibm-eem-manager-0\"}[5m]))",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"event-automation\", pod=\"my-eem-manager-ibm-eem-manager-0\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Event Gateway",
   "type": "timeseries",
   "description": "Resource usage (CPU and memory) of the Event Gateway pod",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{namespace=\"event-automation\", pod=~\"my-eem-gateway-ibm-egw-gateway.*\"}[5m]))",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"event-automation\", pod=~\"my-eem-gateway-ibm-egw-gateway.*\"})",
     "legendFormat": "Memory"
    }
   ]
  }
 ]
}