{
 "title": "Event Endpoint Management (Activity)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Most popular topics (applications)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "last_over_time(eemmanager_options{namespace=\"event-automation\"}[$__interval])",
     "legendFormat": "{{option}}"
    }
   ]
  },
  {
   "title": "Topic options with applications",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(eemmanager_options{namespace=\"event-automation\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "eemmanager_options{namespace=\"event-automation\"}",
     "legendFormat": "{{option}}"
    }
   ]
  },
  {
   "title": "Active clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(eemgateway_connected_clients{namespace=\"event-automation\"})",
     "legendFormat": "clients"
    }
   ]
  },
  {
   "title": "Consumer activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(eemgateway_consumers_bytes_total{namespace=\"event-automation\"}[$__rate_interval]))",
     "legendFormat": "Bytes"
    },
    {
     "expr": "sum(rate(eemgateway_consumers_msgs_total{namespace=\"event-automation\"}[$__rate_interval]))",
     "legendFormat": "Messages"
    }
   ]
  },
  {
   "title": "Producer activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(eemgateway_producers_bytes_total{namespace=\"event-automation\"}[$__rate_interval]))",
     "legendFormat": "Bytes"
    },
    {
     "expr": "sum(rate(eemgateway_producers_msgs_total{namespace=\"event-automation\"}[$__rate_interval]))",
     "legendFormat": "Messages"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Rejected clients",
   "type": "timeseries",
   "description": "Connection attempts (per second) that were rejected by the Event Gateway",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(clientId) (rate(eemgateway_login_failed_total{namespace=\"event-automation\"}[$__rate_interval]))",
     "legendFormat": "login failed ({{clientId}})"
    },
    {
     "expr": "sum by(clientId) (rate(eemgateway_topic_authz_failed_total{namespace=\"event-automation\"}[$__rate_interval]))",
     "legendFormat": "auth failed ({{clientId}})"
    }
   ]
  },
  {
   "title": "Throttled clients",
   "type": "timeseries",
   "description": "A measure of the quota delay applied to Kafka clients attempting to consumer or produce faster than the defined quota",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(clientId) (rate(eemgateway_quota_delay{namespace=\"event-automation\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}