{
 "title": "Event Streams (Health)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Offline partitions",
   "type": "timeseries",
   "description": "An \"offline\" partition is a topic partition that doesn't have an active leader. \n\nThe lack of an active leader will prevent client applications from producing to, or consuming from, a topic partition - the partition will be unavailable until a leader can be restored.\n\nThe number of partitions in this state should normally be zero. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unclean leader elections",
   "type": "timeseries",
   "description": "A leader election is the process for choosing which replica should be used by producer and consumer client applications. \n\nThis should normally be one of the replicas that is in sync, but if there are no in-sync replicas to choose from, the last resort is to select an out-of-sync replica as the leader. \n\nThis results in the loss of some events that were missing on the new leader, and so the number of unclean leader elections should be zero.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_uncleanleaderelections_total{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Under-replicated partitions",
   "type": "timeseries",
   "description": "An under-replicated topic partition is a topic partition where not all of the replicas are keeping up with the partition leader. \n\nThe number of these should be zero for a cluster that is able to keep up with the traffic it is handling. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetcher lag",
   "type": "timeseries",
   "description": "Fetcher lag measures the number of events that follower replicas have still to retrieve from topic partition leaders. It is a measure of whether replication is keeping up, and how far behind the topic replicas are falling.\n\nThe lag should be less than the maximum batch size used by producer applications, indicating that cluster is able to keep up with the traffic it is handling.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(kafka_server_fetcherlagmetrics_consumerlag{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Brokers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active controllers",
   "type": "timeseries",
   "description": "There should be one broker acting as the controller for the cluster. Several critical cluster operations depend on the controller, such as partition leadership management and replica assignment. \n\nIf there is no controller, this will soon lead to problems. \n\nIf there are more than one controllers, this is described as a \"split brain\" and the potential for conflicting decisions by the multiple controllers risks data integrity. \n\nThis value should always be 1. (You may briefly see zero or two while the cluster is transferring the control to a different broker, but this should quickly return to 1.)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of online brokers",
   "type": "timeseries",
   "description": "The high availability enabled by Kafka's design mean that applications can continue to function even after the failure of a broker. As a result, it is important to monitor that all brokers are currently online, as the loss of a broker cannot always be detected by application behaviour. \n\nThe Event Streams cluster created by the tutorial playbook should have three brokers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activebrokercount{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Broker uptime",
   "type": "table",
   "description": "The start time for each of the brokers. \n\nIf any of these times is much more recent than expected, it indicates that a broker has been restarted. ",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "kube_pod_container_state_started{namespace=\"event-automation\", pod=~\"my-kafka-cluster-kafka-0|my-kafka-cluster-kafka-1|my-kafka-cluster-kafka-2\", container=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restart count",
   "type": "gauge",
   "description": "How many times has Kubernetes restarted the Kafka container? \n\nThis should be zero for a healthy broker.",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (kube_pod_container_status_restarts_total{namespace=\"event-automation\", pod=~\"my-kafka-cluster-kafka-0|my-kafka-cluster-kafka-1|my-kafka-cluster-kafka-2\", container=\"kafka\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Disk space remaining (Kafka)",
   "type": "timeseries",
   "description": "Disk space for Kafka brokers should be closely monitored - if Kafka fills the disk space available to it, it leads to error conditions that are difficult to correct. \n\nAn administrator should take action long before the disk becomes full - closely monitoring the remaining disk space for each broker is a key part of this. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{namespace=\"event-automation\", persistentvolumeclaim=~\"data-my-kafka-cluster-kafka-0|data-my-kafka-cluster-kafka-1|data-my-kafka-cluster-kafka-2\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Disk space remaining (ZooKeeper)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{namespace=\"event-automation\", persistentvolumeclaim=~\"data-my-kafka-cluster-zookeeper-0|data-my-kafka-cluster-zookeeper-1|data-my-kafka-cluster-zookeeper-2\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Network request errors (per min)",
   "type": "timeseries",
   "description": "There should be no network errors reported by a healthy cluster. \n\nIf sustained network errors are reported, this will likely impact consumer and producer applications. ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(error) (rate(kafka_network_requestmetrics_errors_total{eventstreams_ibm_com_cluster=\"my-kafka-cluster\", namespace=\"event-automation\", error!=\"NONE\"}[1m])) > 0.9",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}