apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
    name: ep-operator-catalog
    namespace: openshift-marketplace
spec:
    displayName: IBM EP Catalog
    image: icr.io/cpopen/ibm-eventprocessing-operator-catalog:1.4.1
    publisher: IBM
    sourceType: grpc
    updateStrategy:
        registryPoll:
            interval: 45m
