apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-eventprocessing-operator
  namespace: openshift-operators
  labels:
    operators.coreos.com/ibm-eventprocessing.openshift-operators: ''
spec:
  channel: v1.2
  name: ibm-eventprocessing
  source: ep-operator-catalog
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
