---
- name: Install Apache Flink
  hosts: localhost
  connection: local
  vars:
    eventautomation_namespace: "event-automation"
    license_accept: "{{ undef(hint='You need to accept the Event Automation license to continue') }}"
    ibm_entitlement_key: "{{ undef(hint='Provide an Entitled Registry key') }}"

  tasks:
    - name: Install local pre-requisites
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/prerequisites.yaml"

    - name: Check for required variables
      ansible.builtin.assert:
        that:
          - license_accept is defined
          - eventautomation_namespace is defined
          - ibm_entitlement_key is defined

    - name: Setup operator
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/setup-operator.yaml"
      vars:
        catalogsource_name: "flink-operator-catalog"
        catalogsource_template: "{{ playbook_dir }}/templates/01-catalog-source.yaml"
        subscription_name: "flink-kubernetes-operator"
        subscription_template: "{{ playbook_dir }}/templates/02-operator-subscription.yaml"

    - name: Create namespace for Event Automation
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/setup-namespace.yaml"
      vars:
        namespace: "{{ eventautomation_namespace }}"

    - name: Check if an Event Automation truststore has been prepared
      kubernetes.core.k8s_info:
        namespace: "{{ eventautomation_namespace }}"
        kind: Secret
        name: eventautomation-truststore
      register: truststore_setup

    - name: Create truststore if no secret exists
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/create-ea-truststore.yaml"
      when: truststore_setup.resources | length == 0

    - name: Create Flink deployment
      kubernetes.core.k8s:
        validate_certs: false
        state: present
        namespace: "{{ eventautomation_namespace }}"
        template: "{{ playbook_dir }}/templates/03-flink.yaml"
