---
- name: Install Event Endpoint Management
  hosts: localhost
  connection: local
  vars:
    eventautomation_namespace: "{{ undef(hint='Specify the namespace to deploy into') }}"
    license_accept: "{{ undef(hint='You need to accept the Event Automation license to continue') }}"
    ibm_entitlement_key: "{{ undef(hint='Provide an Entitled Registry key') }}"

  tasks:
    - name: Install local pre-requisites
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/prerequisites.yaml"

    - name: Check for required variables
      ansible.builtin.assert:
        that:
          - license_accept is defined
          - eventautomation_namespace is defined
          - ibm_entitlement_key is defined

    - name: Setup operator
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/setup-operator.yaml"
      vars:
        catalogsource_name: "eem-operator-catalog"
        catalogsource_template: "{{ playbook_dir }}/templates/01-catalog-source.yaml"
        subscription_name: "ibm-event-endpoint-management"
        subscription_template: "{{ playbook_dir }}/templates/02-operator-subscription.yaml"

    - name: Create namespace for Event Automation
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/setup-namespace.yaml"
      vars:
        namespace: "{{ eventautomation_namespace }}"

    - name: Create Event Endpoint Management manager
      kubernetes.core.k8s:
        validate_certs: false
        state: present
        namespace: "{{ eventautomation_namespace }}"
        template: "{{ playbook_dir }}/templates/03-eem.yaml"
        wait: true
        wait_condition:
          status: true
          type: Ready
        wait_timeout: 1200

    - name: Get route for use by Event Gateway
      kubernetes.core.k8s_info:
        validate_certs: false
        api_version: route.openshift.io/v1
        kind: Route
        name: my-eem-manager-ibm-eem-gateway
        namespace: "{{ eventautomation_namespace }}"
      register: egw_route

    - name: Create Event Endpoint Management Event Gateway
      vars:
        eem_gateway_route: "https://{{ egw_route.resources[0].spec.host }}"
      kubernetes.core.k8s:
        validate_certs: false
        state: present
        namespace: "{{ eventautomation_namespace }}"
        template: "{{ playbook_dir }}/templates/04-egw.yaml"
        wait: true
        wait_condition:
          status: true
          type: Ready
        wait_timeout: 1200

    - name: Add demo users to the auth config
      kubernetes.core.k8s:
        state: patched
        kind: Secret
        name: my-eem-manager-ibm-eem-user-credentials
        namespace: "{{ eventautomation_namespace }}"
        definition:
          data:
            user-credentials.json: "{{ lookup('template', '{{ playbook_dir }}/templates/05-users.json') | b64encode }}"

    - name: Add demo roles to the auth config
      kubernetes.core.k8s:
        state: patched
        kind: Secret
        name: my-eem-manager-ibm-eem-user-roles
        namespace: "{{ eventautomation_namespace }}"
        definition:
          data:
            user-mapping.json: "{{ lookup('template', '{{ playbook_dir }}/templates/06-roles.json') | b64encode }}"
