apiVersion: events.ibm.com/v1beta1
kind: EventGateway
metadata:
  name: my-eem-gateway
  labels:
    events.ibm.com/manager: my-eem-manager
spec:
  gatewayGroupName: gateway-group
  gatewayID: gateway-1
  license:
    accept: {{ license_accept }}
    license: L-CYBH-K48BZQ
    metric: VIRTUAL_PROCESSOR_CORE
    use: EventAutomationNonProduction
  listeners:
    - name: gateway
      port: 8092
      groups:
        - name: gateway-group
          type: EXPLICIT
          maxNumKafkaBrokers: 20
          endpoint:
            host: eem-gateway-1-{{ eventautomation_namespace }}.{{ cluster_subdomain }}
      tls:
        caSecret:
          secretName:  my-eem-manager-ibm-eem-manager-ca
  template:
    pod:
      spec:
        containers:
          - name: egw
            resources:
              requests:
                cpu: '0.5'
                memory: 512Mi
              limits:
                cpu: '1'
                memory: 1Gi
