apiVersion: events.ibm.com/v1beta1
kind: EventGateway
metadata:
  name: my-eem-gateway
spec:
  managerEndpoint: {{ eem_gateway_route }}
  gatewayGroupName: gateway-group
  gatewayID: gateway-1
  license:
    accept: {{ license_accept }}
    license: L-HRZF-DWHH7A
    metric: VIRTUAL_PROCESSOR_CORE
    use: EventAutomationNonProduction
  replicas: 3
  tls:
    caSecretName: my-eem-manager-ibm-eem-manager-ca
