apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/crunchy-postgres-operator.openshift-operators: ''
  name: crunchy-postgres-operator
  namespace: openshift-operators
spec:
  channel: v5
  installPlanApproval: Automatic
  name: crunchy-postgres-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: postgresoperator.v5.7.1
