apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pgsqldemo
spec:
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
  databaseInitSQL:
    name: pgsqldemo-data-cm
    key: demo_data.sql
  instances:
  - dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
    name: ""
    replicas: 1
  openshift: true
  patroni:
    leaderLeaseDurationSeconds: 30
    port: 8008
    syncPeriodSeconds: 10
  port: 5432
  postgresVersion: 15
  proxy:
    pgBouncer:
      port: 5432
      replicas: 1
  users:
  - name: demouser
    databases:
      - pgsqldemo
    options: SUPERUSER
  - name: pgadmin
    databases:
      - pgsqldemo
